#!/usr/bin/env bash

set -e

DEST=swh-management@inria.fr
AUTHOR=swh-management@inria.fr
TEMPLATE_ID="OGAEXlDiShGabI14j_3LeA"
URL="https://hedgedoc.softwareheritage.org"
DATE=$(date +%G-W%V -d 'monday 12:00')

# Retrieve the template's content
TEMPLATE=$(curl -s "${URL}/${TEMPLATE_ID}/download")
TEMPLATE=$(echo "$TEMPLATE" | sed -e "s/\$DATE/$DATE/g" | sed -e "/^tags:/s/, template//")

# Create a new page initialized with the template content
RESP=$(curl -s -A POST -H "Content-Type: text/markdown" "${URL}/new" --data-binary "$TEMPLATE")
LOCATION=$(echo "$RESP" | awk '{print $4}')

if [ -n "$LOCATION" ] ; then

  /usr/lib/sendmail -t <<EOF
From: Weekly management coordination bot <$AUTHOR>
To: $DEST
Subject: [Weekly management coordination] $DATE pad is open

Dear management team,

Thank you for filling the pad for next management coordination :

    $LOCATION

Expected contents:

- bullet points ready for an initial roundtable, focusing on the high level issues that are relevant for all of us around the table - 3m per person
- status of actions identified in the last meetings

Thank you !

Yours faithfully,
--
The Software Heritage weekly management coordination bot

EOF

fi
