{
 "title": "Node Exporter",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation, Filesystem usage and Predicted time to filesystems filling. This for the Node Exporter version 0.16.0 or later.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": "up{job=\"node\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"node\",instance=\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='node',instance='$instance'} - node_memory_MemFree_bytes{job='node',instance='$instance'} - node_memory_Buffers_bytes{job='node',instance='$instance'} - node_memory_Cached_bytes{job='node',instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='node',instance='$instance'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='node',instance='$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job='node',instance='$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job='node',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='node',instance='$instance'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Fill Up Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job='node',instance='$instance'} - node_filesystem_free_bytes{job='node',instance='$instance'}) / deriv(node_filesystem_free_bytes{job='node',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''}[3d]) > 0",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}