#!/usr/bin/env bash

set -e

DEST=swh-team@inria.fr
AUTHOR=swh-team@inria.fr
TEMPLATE_ID="6YKT5osoST-amJQ0MusH2Q"
URL="https://hedgedoc.softwareheritage.org"
DATE=$(date +%G-W%V -d 'monday 12:00')

# Retrieve the template's content
TEMPLATE=$(curl -s "${URL}/${TEMPLATE_ID}/download")
TEMPLATE=$(echo "$TEMPLATE" | sed -e "s/\$DATE/$DATE/g" | sed -e "/^tags:/s/, template//")

# Create a new page initialized with the template content
RESP=$(curl -s -A POST -H "Content-Type: text/markdown" "${URL}/new" --data-binary "$TEMPLATE")
LOCATION=$(echo "$RESP" | awk '{print $4}')

if [ -n "$LOCATION" ] ; then

  /usr/lib/sendmail -t <<EOF
From: Weekly planning bot <$AUTHOR>
To: $DEST
Subject: [Weekly Planning] Week $DATE

Beep boop, I'm a bot.

Here is the pad for the next weekly planning meeting:

    $LOCATION

Please take a few minutes to pre-fill your part.

Remote attendees:

    https://meet.jit.si/EquivalentCoincidencesVentureOnlySwhTeam

Yours faithfully,
--
The Software Heritage weekly bot
EOF

fi
