#!/bin/bash

DEST=swh-devel@inria.fr

/usr/lib/sendmail -t <<EOF
From: Weekly report bot <swh-devel@inria.fr>
To: $DEST
Subject: [Weekly Report] Week $(date +%G-W%V)

Beep boop, I'm a bot.

This thread will contain reports on what the Software Heritage team members did
over the last week. Please feel free to ask for more details, we'll be glad to
oblige!

Yours faithfully,
-- 
The Software Heritage weekly report bot
EOF
