- name: "swh_scheduler_oneshot"
  scope: database
  cluster: secondary
  database: softwareheritage-scheduler
  interval: '1h'
  help: "Software Heritage Scheduled Oneshot Tasks"
  labels:
    - "type_policy_status"
  values:
    - "count"
  query:  |
           select type ||' '|| status as type_policy_status, count(*) as count
           from task
           where policy='oneshot' group by 1 order by 1

- name: "swh_scheduler_recurring"
  scope: database
  cluster: secondary
  database: softwareheritage-scheduler
  interval: '1h'
  help: "Software Heritage Scheduled Recurring Tasks"
  labels:
    - "type_policy_status"
  values:
    - "count"
  query:  |
           select type ||' '|| status as type_policy_status, count(*) as count
           from task
           where policy='recurring' group by 1 order by 1
